# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-14 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Cinema', max_length=200)),
                ('info', models.TextField(default='Cinema Info...')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Film', max_length=200)),
                ('info', models.TextField(default='Film Info...')),
            ],
        ),
        migrations.CreateModel(
            name='FilmRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Room', max_length=200)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, default=2, max_digits=5)),
                ('booked', models.BooleanField(default='False')),
                ('filmRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.FilmRoom')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Place')),
                ('user', models.ForeignKey(blank=True, default='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Room'),
        ),
        migrations.AddField(
            model_name='filmroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Room'),
        ),
    ]
