# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-14 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_placeroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='room',
        ),
    ]
