# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-30 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cinema', max_length=200)),
                ('description', models.TextField(default='This is Cinema description')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hall', max_length=200)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Movie', max_length=200)),
                ('description', models.TextField(default='This is Movie description')),
            ],
        ),
        migrations.CreateModel(
            name='MovieHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.datetime(2018, 10, 30, 6, 31, 52, 739185, tzinfo=utc))),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BooleanField(default='False')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=5.99, max_digits=6)),
                ('movieHall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.MovieHall')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Seat')),
            ],
        ),
    ]
