# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-30 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_cinema_hall_movie_moviehall_seat_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='sold',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sold',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
