# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181030_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviehall',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
